### ISSUE TITLE
PNG logos for OPCR artwork

### ISSUE THREAD

**Issue by noashavit** [opcr-io/artwork#1]
PNG logos 

![OPCR logo](https://user-images.githubusercontent.com/46575232/213058706-9b012c72-8331-48ef-999c-be6fd15a1f96.png)
![OPCR horizontal - dark background](https://user-images.githubusercontent.com/46575232/213059081-bcab568d-d001-4205-991a-51b399bab7dc.png)
![OPCR horizontal- light background](https://user-images.githubusercontent.com/46575232/213059083-6f874044-53fc-436a-9ca8-d7c9946bdbba.png)
![OPCR - Horizontal 170x62-dark background](https://user-images.githubusercontent.com/46575232/213059341-2b1cca7d-d1d5-482f-94ea-eae281c3b205.png)
![OPCR - Horizontal 170x62-ligth background](https://user-images.githubusercontent.com/46575232/213059344-4ed79623-df2d-403a-9909-eeef9b3458d8.png)
![Open Policy Containers - Horizontal- light background](https://user-images.githubusercontent.com/46575232/213059465-bf56f800-1ea2-4960-8000-d35700493701.png)
![Open Policy Containers - Horizontal- dark background](https://user-images.githubusercontent.com/46575232/213059466-d9a96a0a-64d6-4414-bc13-4fb82a2d65d4.png)
![Open Policy Containers - Stacked-light background](https://user-images.githubusercontent.com/46575232/213059634-4dd6926f-cf99-4c4c-a60a-52057e5bb355.png)
![Open Policy Containers - Stacked- dark background](https://user-images.githubusercontent.com/46575232/213059637-02f72756-e9e8-4acd-85b0-014433adf45a.png)

**Comment by ogazitt** [comment]
Thanks! incorporated.
